### PR TITLE
fix: Ignore pre-release field when parsing versions

### LINKED ISSUE #362: Drivers do not support pre-release versions of tools
Bluebuild v0.9.6 currently panics with the following error on a machine with podman `5.4.0-rc3` installed:

```
Could not determine strategy, need either docker version >=23, podman version >=4, or buildah version >=1.29 to continue
```

I believe this is because many semver comparison functions skip all pre-release versions.
Note that as of writing Fedora 41 Testing, 42, and rawhide all package a pre-release version of podman.

### PR DESCRIPTION
**Pull request by prydom**
Fixes #362.

### CODE REVIEW

**Comment by prydom** [comment]
I haven't tested this yet myself as `onig_sys@69.8.1` won't build for me on my host and I get the following error from the Nix flake:

```
❯ nix run
error: builder for '/nix/store/pmcxv1i94gdv92gmyjczmn80ygkaz135-bluebuild-v0.8.1.drv' failed with exit code 101;
       last 18 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/v5mxgvdx8cpkhb0qjchag8108xsj8k2j-source
       > source root is source
       > Executing cargoSetupPostUnpackHook
       > Finished cargoSetupPostUnpackHook
       > Running phase: patchPhase
       > Executing cargoSetupPostPatchHook
       > Validating consistency between /build/source/Cargo.lock and /build/cargo-vendor-dir/Cargo.lock
       > Finished cargoSetupPostPatchHook
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > Running phase: buildPhase
       > Executing cargoBuildHook
       > ++ env CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/ln6zld1ia7rxddmxgbpfhrmb42rbxdw8-gcc-wrapper-13.2.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/ln6zld1ia7rxddmxgbpfhrmb42rbxdw8-gcc-wrapper-13.2.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/ln6zld1ia7rxddmxgbpfhrmb42rbxdw8-gcc-wrapper-13.2.0/bin/cc CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/ln6zld1ia7rxddmxgbpfhrmb42rbxdw8-gcc-wrapper-13.2.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/ln6zld1ia7rxddmxgbpfhrmb42rbxdw8-gcc-wrapper-13.2.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/ln6zld1ia7rxddmxgbpfhrmb42rbxdw8-gcc-wrapper-13.2.0/bin/cc CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu HOST_CC=/nix/store/ln6zld1ia7rxddmxgbpfhrmb42rbxdw8-gcc-wrapper-13.2.0/bin/cc HOST_CXX=/nix/store/ln6zld1ia7rxddmxgbpfhrmb42rbxdw8-gcc-wrapper-13.2.0/bin/c++ cargo build -j 16 --target x86_64-unknown-linux-gnu --frozen --profile release
       > error: failed to parse lock file at: /build/source/Cargo.lock
       >
       > Caused by:
       >   lock file version 4 requires `-Znext-lockfile-bump`
       For full logs, run 'nix log /nix/store/pmcxv1i94gdv92gmyjczmn80ygkaz135-bluebuild-v0.8.1.drv'.
```

I will test the CI built binary once it's available.

**Comment by prydom** [comment]
Ok, I was able to get this to build in a distrobox. It doesn't seem to have resolve the issue yet so I'll keep poking at it:

```
Could not determine strategy, need either docker version >=23.0.0-0, podman version >=4.0.0-0, or buildah version >=1.29.0-0 to continue
```

Marking this PR as a draft.

**Comment by prydom** [comment]
I've cleared the pre-release field in the parsed version. I've tested it and the comparator works now.

I'm not a Rust developer so I'm unsure if what I've written is idiomatic, so please review it for style.

**Comment by prydom** [comment]
Force pushed a better commit comment. Nothing else changed.

File: utils/src/semver.rs [hunk 1]
```diff
@@ -23,9 +24,14 @@ impl<'de> Deserialize<'de> for Version {
...
-            .map(Self)
+        let Ok(mut parsed_ver) = lenient_semver::parse(&ver) else {
+            return Err(D::Error::custom(format!(
+                "Failed to deserialize version {ver}"
+            )));
+        };
+        // delete pre-release field or we can never match pre-release versions of tools
+        parsed_ver.pre = Prerelease::EMPTY;
+        Some(Self(parsed_ver))
             .ok_or_else(|| D::Error::custom(format!("Failed to deserialize version {ver}")))
```
Comment (gmpinder) [inline utils/src/semver.rs:35]:
```suggestion
        Ok(Self(parsed_ver))
```
Pretty good, just needs to be `Ok` since the return type of the function is `Result`. The `Some` variant is for the `Option` type.

**Review by gmpinder — APPROVED** [review]

File: utils/src/semver.rs (hunk 1 above)
Comment (prydom) [reply utils/src/semver.rs]: I wasn't 100% sure if we wanted a Result with the error intact (e.g. for downstream code to be able to reference it) but I assume it's actually a derived type where the error is just lost because we know the value inside the result isn't None.

Thanks for the review.
